name = "mindshift-demo"
main = "src/index.ts"
compatibility_date = "2026-04-30"

[[d1_databases]]
binding = "DB"
database_name = "mindshift-demo-prod"
database_id = "9f8a3741-af9d-4e8b-b973-50967a6fd0e6"
